const questions = [
  {name:'נפוליאון בונפרטה',image:'images/napoleon.jpg',source:'Wikimedia Commons — ז׳אק־לואי דויד, נפוליאון בחדר עבודתו',categories:['מנהיגים ומדינאים','מלוכה ואימפריות'],difficulty:'בינוני',options:['נפוליאון בונפרטה','לואי ה־14','הדוכס מוולינגטון','פרידריך הגדול'],explanation:'זהו נפוליאון בונפרטה. הדיוקן מציג אותו במדי קצין בחדר עבודתו, והוא אחד הייצוגים המוכרים ביותר שלו.'},
  {name:'סולימאן המפואר',image:'images/suleiman.jpg',source:'Wikimedia Commons — מלכיור לורק, דיוקן סולימאן הראשון, 1562',categories:['מלוכה ואימפריות'],difficulty:'קשה',options:['מהמט השני','סולימאן המפואר','סלים הראשון','מוראד השלישי'],explanation:'זהו סולימאן הראשון, המכונה סולימאן המפואר, מן הסולטאנים הבולטים של האימפריה העות׳מאנית.'},
  {name:'תיאודור הרצל',image:'images/herzl.jpg',source:'Wikimedia Commons — דיוקן תיאודור הרצל, נחלת הכלל',categories:['מנהיגים ומדינאים'],difficulty:'בינוני',options:['חיים ויצמן','מקס נורדאו','תיאודור הרצל','נחום סוקולוב'],explanation:'זהו תיאודור הרצל. הזקן הארוך, השיער והצילום מן הצד הפכו למראה מזוהה מאוד עם חוזה המדינה.'},
  {name:'אברהם לינקולן',image:'images/lincoln.jpg',source:'Wikimedia Commons — תצלום עמידה של אברהם לינקולן, 1863',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['אברהם לינקולן','יוליסס גרנט','אנדרו ג׳ונסון','ג׳פרסון דייוויס'],explanation:'זהו אברהם לינקולן, הנשיא ה־16 של ארצות הברית.'},
  {name:'ג׳ורג׳ וושינגטון',image:'images/washington.jpg',source:'Wikimedia Commons — גילברט סטיוארט, ג׳ורג׳ וושינגטון, 1796',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['ג׳ורג׳ וושינגטון','תומאס ג׳פרסון','ג׳ון אדמס','ג׳יימס מדיסון'],explanation:'זהו ג׳ורג׳ וושינגטון, הנשיא הראשון של ארצות הברית.'},
  {name:'המלכה ויקטוריה',image:'images/victoria.jpg',source:'Wikimedia Commons — רוג׳ר פנטון, דיוקן המלכה ויקטוריה, 1854',categories:['מלוכה ואימפריות'],difficulty:'בינוני',options:['המלכה ויקטוריה','המלכה אן','קתרינה הגדולה','מריה תרזה'],explanation:'זוהי המלכה ויקטוריה, ששלטה בבריטניה בשנים 1837–1901 ונתנה את שמה לתקופה הוויקטוריאנית.'},
  {name:'מארי קירי',image:'images/curie.jpg',source:'Wikimedia Commons — דיוקן מארי קירי, בערך 1921',categories:['מדע והגות'],difficulty:'קל',options:['מארי קירי','עדה לאבלייס','רוזלינד פרנקלין','ליזה מייטנר'],explanation:'זוהי מארי קירי, מחלוצות חקר הרדיואקטיביות והאדם הראשון שזכה בשני פרסי נובל בשני תחומים מדעיים שונים.'},
  {name:'אייזק ניוטון',image:'images/newton.jpg',source:'Wikimedia Commons — גודפרי נלר, דיוקן אייזק ניוטון',categories:['מדע והגות'],difficulty:'בינוני',options:['אייזק ניוטון','גלילאו גליליי','יוהנס קפלר','רנה דקארט'],explanation:'זהו אייזק ניוטון, מן המדענים המשפיעים בתולדות הפיזיקה והמתמטיקה.'},
  {name:'אליזבת הראשונה',image:'images/elizabeth1.jpg',source:'Wikimedia Commons — דיוקן ההכתרה של אליזבת הראשונה, העתק מראשית המאה ה־17',categories:['מלוכה ואימפריות'],difficulty:'בינוני',options:['אליזבת הראשונה','מרי הראשונה','אן בולין','מרי מלכת הסקוטים'],explanation:'זוהי אליזבת הראשונה, מלכת אנגליה ואירלנד בשנים 1558–1603.'},
  {name:'יוליוס קיסר',image:'images/caesar.jpg',source:'Wikimedia Commons — פסל שיש של יוליוס קיסר מן המאה הראשונה לספירה',categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'קשה',options:['יוליוס קיסר','אוגוסטוס','מרקוס אורליוס','קונסטנטינוס הגדול'],explanation:'זהו יוליוס קיסר, המצביא והמדינאי הרומי שמילא תפקיד מכריע בסופה של הרפובליקה הרומית.'}
];

let activeQuestions=[],index=0,score=0,answered=false,audioContext=null;
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function getAudioContext(){if(!audioContext){const A=window.AudioContext||window.webkitAudioContext;if(A)audioContext=new A();}return audioContext;}
function playTone(f,s,d,t='sine',v=.12){const c=getAudioContext();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.setValueAtTime(f,s);g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(v,s+.015);g.gain.exponentialRampToValueAtTime(.0001,s+d);o.connect(g);g.connect(c.destination);o.start(s);o.stop(s+d+.02);}
function playCorrectSound(){const c=getAudioContext();if(!c)return;if(c.state==='suspended')c.resume();const n=c.currentTime+.02;playTone(523.25,n,.16,'triangle',.11);playTone(659.25,n+.12,.16,'triangle',.11);playTone(783.99,n+.24,.30,'triangle',.13);}
function playWrongSound(){const c=getAudioContext();if(!c)return;if(c.state==='suspended')c.resume();const n=c.currentTime+.02;playTone(220,n,.22,'sawtooth',.07);playTone(164.81,n+.16,.34,'sawtooth',.06);}
const setup=document.getElementById('setup'),game=document.getElementById('game'),result=document.getElementById('result'),categorySelect=document.getElementById('categorySelect'),difficultySelect=document.getElementById('difficultySelect'),setupMessage=document.getElementById('setupMessage'),startGameButton=document.getElementById('startGame'),portrait=document.getElementById('portrait'),caption=document.getElementById('sourceCaption'),answers=document.getElementById('answers'),feedback=document.getElementById('feedback'),next=document.getElementById('next'),restart=document.getElementById('restart'),playAgain=document.getElementById('playAgain'),questionNumber=document.getElementById('questionNumber'),totalQuestions=document.getElementById('totalQuestions'),scoreNode=document.getElementById('score'),finalScore=document.getElementById('finalScore'),finalTotal=document.getElementById('finalTotal'),categoryTag=document.getElementById('categoryTag'),difficultyTag=document.getElementById('difficultyTag');
function startGame(){const cat=categorySelect.value,diff=difficultySelect.value;const filtered=questions.filter(q=>(cat==='all'||q.categories.includes(cat))&&(diff==='all'||q.difficulty===diff));if(!filtered.length){setupMessage.textContent='אין כרגע שאלות בשילוב הזה. בחרו "כל הרמות" או רמת קושי אחרת.';return;}setupMessage.textContent='';activeQuestions=shuffle(filtered);index=0;score=0;setup.classList.add('hidden');result.classList.add('hidden');game.classList.remove('hidden');totalQuestions.textContent=activeQuestions.length;finalTotal.textContent=activeQuestions.length;renderQuestion();}
function renderQuestion(){answered=false;next.disabled=true;feedback.className='feedback';feedback.textContent='';const q=activeQuestions[index];questionNumber.textContent=index+1;scoreNode.textContent=score;portrait.src=q.image;portrait.alt=`דיוקן לזיהוי — שאלה ${index+1}`;caption.textContent='';caption.hidden=true;categoryTag.textContent=q.categories.join(' · ');difficultyTag.textContent=`רמה: ${q.difficulty}`;answers.innerHTML='';shuffle(q.options).forEach(option=>{const b=document.createElement('button');b.type='button';b.textContent=option;b.addEventListener('click',()=>chooseAnswer(b,option));answers.appendChild(b);});next.textContent=index===activeQuestions.length-1?'לתוצאה':'לשאלה הבאה';}
function chooseAnswer(clickedButton,option){if(answered)return;answered=true;const q=activeQuestions[index];[...answers.children].forEach(b=>{b.disabled=true;if(b.textContent===q.name)b.classList.add('correct');});if(option===q.name){score++;scoreNode.textContent=score;playCorrectSound();feedback.innerHTML=`<strong>נכון! ✅</strong><br>${q.explanation}`;}else{clickedButton.classList.add('wrong');playWrongSound();feedback.innerHTML=`<strong>לא הפעם ❌</strong><br>התשובה הנכונה היא <b>${q.name}</b>.<br>${q.explanation}`;}caption.textContent=q.source;caption.hidden=false;feedback.classList.add('show');next.disabled=false;}
function showResult(){game.classList.add('hidden');result.classList.remove('hidden');finalScore.textContent=score;}
function backToSetup(){game.classList.add('hidden');result.classList.add('hidden');setup.classList.remove('hidden');setupMessage.textContent='';}
next.addEventListener('click',()=>{if(!answered)return;if(index<activeQuestions.length-1){index++;renderQuestion();}else showResult();});restart.addEventListener('click',backToSetup);playAgain.addEventListener('click',backToSetup);startGameButton.addEventListener('click',startGame);portrait.addEventListener('error',()=>{caption.textContent='לא ניתן לטעון את התמונה כרגע. נסה לרענן את הדף.';caption.hidden=false;});