const questions = [
  {name:'נפוליאון בונפרטה',image:'images/napoleon.jpg',source:'Wikimedia Commons — ז׳אק־לואי דויד, נפוליאון בחדר עבודתו',categories:['מנהיגים ומדינאים','מלוכה ואימפריות'],difficulty:'בינוני',options:['נפוליאון בונפרטה','לואי ה־14','הדוכס מוולינגטון','פרידריך הגדול'],explanation:'זהו נפוליאון בונפרטה. הדיוקן מציג אותו במדי קצין בחדר עבודתו, והוא אחד הייצוגים המוכרים ביותר שלו.'},
  {name:'סולימאן המפואר',image:'images/suleiman.jpg',source:'Wikimedia Commons — מלכיור לורק, דיוקן סולימאן הראשון, 1562',categories:['מלוכה ואימפריות'],difficulty:'קשה',options:['מהמט השני','סולימאן המפואר','סלים הראשון','מוראד השלישי'],explanation:'זהו סולימאן הראשון, המכונה סולימאן המפואר, מן הסולטאנים הבולטים של האימפריה העות׳מאנית.'},
  {name:'תיאודור הרצל',image:'images/herzl.jpg',source:'Wikimedia Commons — דיוקן תיאודור הרצל, נחלת הכלל',categories:['מנהיגים ומדינאים'],difficulty:'בינוני',options:['חיים ויצמן','מקס נורדאו','תיאודור הרצל','נחום סוקולוב'],explanation:'זהו תיאודור הרצל. הזקן הארוך, השיער והצילום מן הצד הפכו למראה מזוהה מאוד עם חוזה המדינה.'},
  {name:'אברהם לינקולן',image:'images/lincoln.jpg',source:'Wikimedia Commons — תצלום עמידה של אברהם לינקולן, 1863',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['אברהם לינקולן','יוליסס גרנט','אנדרו ג׳ונסון','ג׳פרסון דייוויס'],explanation:'זהו אברהם לינקולן, הנשיא ה־16 של ארצות הברית.'},
  {name:'ג׳ורג׳ וושינגטון',image:'images/washington.jpg',source:'Wikimedia Commons — גילברט סטיוארט, ג׳ורג׳ וושינגטון, 1796',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['ג׳ורג׳ וושינגטון','תומאס ג׳פרסון','ג׳ון אדמס','ג׳יימס מדיסון'],explanation:'זהו ג׳ורג׳ וושינגטון, הנשיא הראשון של ארצות הברית.'},
  {name:'המלכה ויקטוריה',image:'images/victoria.jpg',source:'Wikimedia Commons — רוג׳ר פנטון, דיוקן המלכה ויקטוריה, 1854',categories:['מלוכה ואימפריות'],difficulty:'בינוני',options:['המלכה ויקטוריה','המלכה אן','קתרינה הגדולה','מריה תרזה'],explanation:'זוהי המלכה ויקטוריה, ששלטה בבריטניה בשנים 1837–1901 ונתנה את שמה לתקופה הוויקטוריאנית.'},
  {name:'מארי קירי',image:'images/curie.jpg',source:'Wikimedia Commons — דיוקן מארי קירי, בערך 1921',categories:['מדע והגות'],difficulty:'קל',options:['מארי קירי','עדה לאבלייס','רוזלינד פרנקלין','ליזה מייטנר'],explanation:'זוהי מארי קירי, מחלוצות חקר הרדיואקטיביות והאדם הראשון שזכה בשני פרסי נובל בשני תחומים מדעיים שונים.'},
  {name:'אייזק ניוטון',image:'images/newton.jpg',source:'Wikimedia Commons — גודפרי נלר, דיוקן אייזק ניוטון',categories:['מדע והגות'],difficulty:'בינוני',options:['אייזק ניוטון','גלילאו גליליי','יוהנס קפלר','רנה דקארט'],explanation:'זהו אייזק ניוטון, מן המדענים המשפיעים בתולדות הפיזיקה והמתמטיקה.'},
  {name:'אליזבת הראשונה',image:'images/elizabeth1.jpg',source:'Wikimedia Commons — דיוקן ההכתרה של אליזבת הראשונה, העתק מראשית המאה ה־17',categories:['מלוכה ואימפריות'],difficulty:'בינוני',options:['אליזבת הראשונה','מרי הראשונה','אן בולין','מרי מלכת הסקוטים'],explanation:'זוהי אליזבת הראשונה, מלכת אנגליה ואירלנד בשנים 1558–1603.'},
  {name:'יוליוס קיסר',image:'images/caesar.jpg',source:'Wikimedia Commons — פסל שיש של יוליוס קיסר מן המאה הראשונה לספירה',categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'קשה',options:['יוליוס קיסר','אוגוסטוס','מרקוס אורליוס','קונסטנטינוס הגדול'],explanation:'זהו יוליוס קיסר, המצביא והמדינאי הרומי שמילא תפקיד מכריע בסופה של הרפובליקה הרומית.'},
  {name:'צ׳ארלס דרווין',image:'images/darwin.jpg',source:'Wikimedia Commons — דיוקן צ׳ארלס דרווין',categories:['מדע והגות'],difficulty:'קל',options:['צ׳ארלס דרווין','גרגור מנדל','לואי פסטר','מייקל פאראדיי'],explanation:'זהו צ׳ארלס דרווין, חוקר הטבע שפיתח את תורת האבולוציה באמצעות ברירה טבעית.'},
  {name:'אלכסנדר גרהם בל',image:'images/bell.jpg',source:'Wikimedia Commons — דיוקן אלכסנדר גרהם בל',categories:['מדע והגות'],difficulty:'בינוני',options:['אלכסנדר גרהם בל','תומאס אדיסון','גוליילמו מרקוני','סמואל מורס'],explanation:'זהו אלכסנדר גרהם בל, ממציא ומדען המזוהה במיוחד עם פיתוח הטלפון.'},
  {name:'פלורנס נייטינגייל',image:'images/nightingale.jpg',source:'Wikimedia Commons — דיוקן פלורנס נייטינגייל',categories:['מדע והגות'],difficulty:'בינוני',options:['פלורנס נייטינגייל','קלרה ברטון','אמילין פנקהרסט','אליזבת בלקוול'],explanation:'זוהי פלורנס נייטינגייל, מן הדמויות המרכזיות בהתפתחות הסיעוד המודרני וברפורמה של בתי חולים.'},
  {name:'דוד בן־גוריון',image:'images/bengurion.jpg',source:'Wikimedia Commons — דיוקן דוד בן־גוריון',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['דוד בן־גוריון','משה שרת','לוי אשכול','חיים ויצמן'],explanation:'זהו דוד בן־גוריון, ראש הממשלה הראשון של מדינת ישראל ומן המנהיגים המרכזיים בהקמתה.'},
  {name:'גולדה מאיר',image:'images/golda.jpg',source:'Wikimedia Commons — דיוקן גולדה מאיר',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['גולדה מאיר','אינדירה גנדי','מרגרט תאצ׳ר','אלינור רוזוולט'],explanation:'זוהי גולדה מאיר, שכיהנה כראש ממשלת ישראל בשנים 1969–1974.'},
  {name:'פיוטר הגדול',image:'images/peter.jpg',source:'Wikimedia Commons — דיוקן פיוטר הגדול',categories:['מלוכה ואימפריות'],difficulty:'בינוני',options:['פיוטר הגדול','איוואן האיום','אלכסנדר הראשון','ניקולאי הראשון'],explanation:'זהו פיוטר הראשון, פיוטר הגדול, הצאר הרוסי שקידם רפורמות נרחבות והפך את רוסיה למעצמה אירופית מרכזית.'},
  {name:'סוקרטס',image:'images/socrates.jpg',source:'Wikimedia Commons — פסל דיוקן של סוקרטס',categories:['העת העתיקה','מדע והגות'],difficulty:'בינוני',options:['סוקרטס','אפלטון','אריסטו','דיוגנס'],explanation:'זהו סוקרטס, מן הפילוסופים החשובים של אתונה הקלאסית ומורו של אפלטון.'},
  {name:'אפלטון',image:'images/plato.png',source:'Wikimedia Commons — פסל דיוקן של אפלטון',categories:['העת העתיקה','מדע והגות'],difficulty:'קשה',options:['אפלטון','סוקרטס','אריסטו','פריקלס'],explanation:'זהו אפלטון, תלמידו של סוקרטס ומייסד האקדמיה באתונה.'},
  {name:'גלילאו גליליי',image:'images/galileo.jpg',source:'Wikimedia Commons — דיוקן גלילאו גליליי',categories:['מדע והגות'],difficulty:'בינוני',options:['גלילאו גליליי','יוהנס קפלר','ניקולאוס קופרניקוס','טיכו ברהה'],explanation:'זהו גלילאו גליליי, מדען איטלקי שתרם תרומות יסוד לאסטרונומיה, לפיזיקה ולשימוש המדעי בטלסקופ.'},
  {name:'ניקולה טסלה',image:'images/tesla.jpg',source:'Wikimedia Commons — ניקולה טסלה עם ציוד מעבדתו',categories:['מדע והגות'],difficulty:'קל',options:['ניקולה טסלה','תומאס אדיסון','ג׳ורג׳ וסטינגהאוס','היינריך הרץ'],explanation:'זהו ניקולה טסלה, ממציא ומהנדס חשמל שנודע במיוחד בעבודתו על מערכות זרם חילופין.'},
  {name:'לאונרדו דה וינצ׳י',image:'images/leonardo.jpg',source:'Wikimedia Commons — דיוקן המיוחס ללאונרדו דה וינצ׳י',categories:['מדע והגות'],difficulty:'קל',options:['לאונרדו דה וינצ׳י','מיכלאנג׳לו','רפאל','דונטלו'],explanation:'זהו דיוקן המיוחס ללאונרדו דה וינצ׳י, אמן, מהנדס וחוקר מרכזי של הרנסאנס.'},
  {name:'לואי ה־14',image:'images/louis14.jpg',source:'Wikimedia Commons — דיוקן לואי ה־14 מלך צרפת',categories:['מלוכה ואימפריות'],difficulty:'קל',options:['לואי ה־14','לואי ה־16','שארל השני','פיליפ השני'],explanation:'זהו לואי ה־14, מלך צרפת שנודע בכינוי מלך השמש ושלט יותר משבעים שנה.'},
  {name:'יקטרינה הגדולה',image:'images/catherine.jpg',source:'Wikimedia Commons — דיוקן יקטרינה השנייה',categories:['מלוכה ואימפריות'],difficulty:'קל',options:['יקטרינה הגדולה','מריה תרזה','אליזבת מרוסיה','המלכה ויקטוריה'],explanation:'זוהי יקטרינה השנייה, יקטרינה הגדולה, קיסרית רוסיה מן הדמויות המרכזיות של המאה ה־18.'},
  {name:'אוגוסטוס',image:'images/augustus.jpg',source:'Wikimedia Commons — אוגוסטוס מפרימה פורטה',categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'קל',options:['אוגוסטוס','יוליוס קיסר','טיבריוס','טראיאנוס'],explanation:'זהו אוגוסטוס, הקיסר הראשון של האימפריה הרומית ויורשו הפוליטי של יוליוס קיסר.'},
  {name:'מרקוס אורליוס',image:'images/aurelius.png',source:'Wikimedia Commons — פסל דיוקן של מרקוס אורליוס',categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'קשה',options:['מרקוס אורליוס','אדריאנוס','אנטונינוס פיוס','ספטימיוס סוורוס'],explanation:'זהו מרקוס אורליוס, קיסר רומי ופילוסוף סטואי, מחבר הספר הגיונות.'},
  {name:'אוטו פון ביסמרק',image:'images/bismarck.jpg',source:'Wikimedia Commons — דיוקן אוטו פון ביסמרק',categories:['מנהיגים ומדינאים'],difficulty:'קשה',options:['אוטו פון ביסמרק','הלמוט פון מולטקה','הקייזר וילהלם השני','קלמנס פון מטרניך'],explanation:'זהו אוטו פון ביסמרק, הקנצלר הפרוסי והגרמני שמילא תפקיד מרכזי באיחוד גרמניה במאה ה־19.'},
  {name:'מהטמה גנדי',image:'images/gandhi.jpg',source:'Wikimedia Commons — דיוקן מהטמה גנדי, 1931',categories:['מנהיגים ומדינאים'],difficulty:'קל',options:['מהטמה גנדי','ג׳ווהרלל נהרו','מוחמד עלי ג׳ינה','רבינדרנת טאגור'],explanation:'זהו מהטמה גנדי, ממנהיגי מאבק העצמאות ההודי ומזוהה עם התנגדות לא־אלימה.'},
  {name:'ז׳אן ד׳ארק',image:'images/joan.jpg',source:'Wikimedia Commons — מיניאטורה של ז׳אן ד׳ארק',categories:['מנהיגים ומדינאים'],difficulty:'בינוני',options:['ז׳אן ד׳ארק','אלינור מאקוויטניה','קתרין דה מדיצ׳י','מרגרט מאנז׳ו'],explanation:'זוהי ז׳אן ד׳ארק, הגיבורה הצרפתייה של מלחמת מאה השנים שהפכה לסמל לאומי בצרפת.'},
  {name:'אלברט איינשטיין',image:'images/einstein.jpg',source:'Wikimedia Commons — דיוקן אלברט איינשטיין, 1930',categories:['מדע והגות'],difficulty:'קל',options:['אלברט איינשטיין','נילס בוהר','מקס פלאנק','ארנסט רתרפורד'],explanation:'זהו אלברט איינשטיין, הפיזיקאי שפיתח את תורת היחסות וזכה בפרס נובל לפיזיקה.'}
];

const triviaQuestions = [
 {type:'knowledge',question:'מי פיתח את תורת היחסות?',answer:'אלברט איינשטיין',options:['אלברט איינשטיין','אייזק ניוטון','גלילאו גליליי','ניקולה טסלה'],categories:['מדע והגות'],difficulty:'קל',explanation:'אלברט איינשטיין פיתח את תורות היחסות הפרטית והכללית.'},
 {type:'knowledge',question:'מי מזוהה עם תורת האבולוציה באמצעות ברירה טבעית?',answer:'צ׳ארלס דרווין',options:['צ׳ארלס דרווין','גרגור מנדל','לואי פסטר','מארי קירי'],categories:['מדע והגות'],difficulty:'קל',explanation:'צ׳ארלס דרווין ניסח את רעיון האבולוציה באמצעות ברירה טבעית.'},
 {type:'knowledge',question:'מי היה ראש הממשלה הראשון של מדינת ישראל?',answer:'דוד בן־גוריון',options:['דוד בן־גוריון','משה שרת','לוי אשכול','חיים ויצמן'],categories:['מנהיגים ומדינאים'],difficulty:'קל',explanation:'דוד בן־גוריון היה ראש הממשלה הראשון והכריז על הקמת המדינה.'},
 {type:'knowledge',question:'מי ייסד את האקדמיה באתונה?',answer:'אפלטון',options:['אפלטון','סוקרטס','אריסטו','פריקלס'],categories:['העת העתיקה','מדע והגות'],difficulty:'בינוני',explanation:'אפלטון ייסד באתונה את האקדמיה, מן המוסדות החשובים בתולדות הפילוסופיה.'},
 {type:'knowledge',question:'איזה שליט צרפתי נודע בכינוי „מלך השמש”?',answer:'לואי ה־14',options:['לואי ה־14','נפוליאון בונפרטה','לואי ה־16','שארל השני'],categories:['מלוכה ואימפריות'],difficulty:'קל',explanation:'לואי ה־14 נודע בכינוי „מלך השמש”.'},
 {type:'knowledge',question:'מי מילא תפקיד מרכזי באיחוד גרמניה במאה ה־19?',answer:'אוטו פון ביסמרק',options:['אוטו פון ביסמרק','נפוליאון','מטרניך','גריבלדי'],categories:['מנהיגים ומדינאים'],difficulty:'בינוני',explanation:'ביסמרק הוביל את התהליך המדיני שהביא לאיחוד גרמניה ב־1871.'},
 {type:'knowledge',question:'מי מזוהה במיוחד עם פיתוח הטלפון?',answer:'אלכסנדר גרהם בל',options:['אלכסנדר גרהם בל','סמואל מורס','תומאס אדיסון','ניקולה טסלה'],categories:['מדע והגות'],difficulty:'קל',explanation:'אלכסנדר גרהם בל מזוהה עם פיתוחו ורישומו של הטלפון המעשי.'},
 {type:'knowledge',question:'איזה קיסר רומי כתב את „הגיונות”?',answer:'מרקוס אורליוס',options:['מרקוס אורליוס','אוגוסטוס','נירון','טראיאנוס'],categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'קשה',explanation:'„הגיונות” הוא חיבורו הפילוסופי הסטואי של הקיסר מרקוס אורליוס.'},
 {type:'date',question:'באיזו שנה הוכרזה מדינת ישראל?',answer:'1948',options:['1948','1945','1950','1956'],categories:['מנהיגים ומדינאים'],difficulty:'קל',explanation:'הכרזת העצמאות התקיימה ב־14 במאי 1948.'},
 {type:'date',question:'באיזו שנה נערך הקונגרס הציוני הראשון בבאזל?',answer:'1897',options:['1897','1882','1903','1917'],categories:['מנהיגים ומדינאים'],difficulty:'בינוני',explanation:'הקונגרס הציוני הראשון, ביוזמת הרצל, נערך בבאזל באוגוסט 1897.'},
 {type:'date',question:'באיזו שנה נפוליאון הוכתר לקיסר הצרפתים?',answer:'1804',options:['1804','1789','1812','1815'],categories:['מלוכה ואימפריות','מנהיגים ומדינאים'],difficulty:'בינוני',explanation:'נפוליאון הוכתר לקיסר בדצמבר 1804.'},
 {type:'date',question:'באיזו שנה הסתיימה מלחמת העולם השנייה באירופה?',answer:'1945',options:['1945','1939','1944','1948'],categories:['מנהיגים ומדינאים'],difficulty:'קל',explanation:'גרמניה הנאצית נכנעה במאי 1945.'},
 {type:'date',question:'באיזו שנה החל שלטונה של המלכה ויקטוריה?',answer:'1837',options:['1837','1815','1848','1901'],categories:['מלוכה ואימפריות'],difficulty:'בינוני',explanation:'ויקטוריה עלתה לכס המלוכה הבריטי בשנת 1837.'},
 {type:'date',question:'באיזו שנה הוקמה הקיסרות הגרמנית המאוחדת?',answer:'1871',options:['1871','1848','1866','1914'],categories:['מנהיגים ומדינאים'],difficulty:'קשה',explanation:'הקיסרות הגרמנית הוכרזה בינואר 1871 לאחר המלחמה הפרנקו־פרוסית.'},
 {type:'earlier',question:'מה קרה קודם?',answer:'הקונגרס הציוני הראשון',options:['הקונגרס הציוני הראשון','הכרזת מדינת ישראל'],categories:['מנהיגים ומדינאים'],difficulty:'קל',explanation:'הקונגרס הציוני הראשון נערך ב־1897; מדינת ישראל הוכרזה ב־1948.'},
 {type:'earlier',question:'מי חי קודם?',answer:'סוקרטס',options:['סוקרטס','אוגוסטוס'],categories:['העת העתיקה','מדע והגות'],difficulty:'בינוני',explanation:'סוקרטס חי במאה החמישית לפנה״ס; אוגוסטוס נולד בשנת 63 לפנה״ס.'},
 {type:'earlier',question:'מי נולד קודם?',answer:'גלילאו גליליי',options:['גלילאו גליליי','אייזק ניוטון'],categories:['מדע והגות'],difficulty:'בינוני',explanation:'גלילאו נולד ב־1564, וניוטון ב־1642 לפי הלוח הגרגוריאני המקובל.'},
 {type:'earlier',question:'מי שלט קודם?',answer:'סולימאן המפואר',options:['סולימאן המפואר','לואי ה־14'],categories:['מלוכה ואימפריות'],difficulty:'בינוני',explanation:'סולימאן שלט במאה ה־16; לואי ה־14 החל למלוך במאה ה־17.'},
 {type:'earlier',question:'מי נולד קודם?',answer:'לאונרדו דה וינצ׳י',options:['לאונרדו דה וינצ׳י','גלילאו גליליי'],categories:['מדע והגות'],difficulty:'קל',explanation:'לאונרדו נולד ב־1452; גלילאו ב־1564.'},
 {type:'truefalse',question:'מארי קירי זכתה בפרסי נובל בשני תחומים מדעיים שונים.',answer:'נכון',options:['נכון','לא נכון'],categories:['מדע והגות'],difficulty:'קל',explanation:'נכון. קירי זכתה בנובל לפיזיקה ובנובל לכימיה.'},
 {type:'truefalse',question:'אוגוסטוס היה הקיסר הראשון של האימפריה הרומית.',answer:'נכון',options:['נכון','לא נכון'],categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'קל',explanation:'נכון. אוגוסטוס נחשב לקיסר הרומי הראשון.'},
 {type:'truefalse',question:'סוקרטס היה תלמידו של אפלטון.',answer:'לא נכון',options:['נכון','לא נכון'],categories:['העת העתיקה','מדע והגות'],difficulty:'בינוני',explanation:'לא נכון. אפלטון היה תלמידו של סוקרטס.'},
 {type:'truefalse',question:'גולדה מאיר כיהנה כראש ממשלת ישראל.',answer:'נכון',options:['נכון','לא נכון'],categories:['מנהיגים ומדינאים'],difficulty:'קל',explanation:'נכון. גולדה מאיר כיהנה כראש ממשלה בשנים 1969–1974.'},
 {type:'truefalse',question:'ניקולה טסלה מזוהה במיוחד עם מערכות זרם חילופין.',answer:'נכון',options:['נכון','לא נכון'],categories:['מדע והגות'],difficulty:'קל',explanation:'נכון. עבודתו של טסלה הייתה מרכזית בפיתוח מערכות זרם חילופין.'},
 {type:'truefalse',question:'אליזבת הראשונה הייתה בתה של המלכה ויקטוריה.',answer:'לא נכון',options:['נכון','לא נכון'],categories:['מלוכה ואימפריות'],difficulty:'קל',explanation:'לא נכון. אליזבת הראשונה חיה במאה ה־16, מאות שנים לפני ויקטוריה.'},
 {type:'truefalse',question:'יוליוס קיסר היה הקיסר הרומי הראשון.',answer:'לא נכון',options:['נכון','לא נכון'],categories:['העת העתיקה','מנהיגים ומדינאים'],difficulty:'בינוני',explanation:'לא נכון. אוגוסטוס, יורשו, נחשב לקיסר הרומי הראשון.'}
];
const portraitQuestions=questions.map(q=>({...q,type:'portrait',question:'מי הדמות ההיסטורית שבתמונה?',answer:q.name}));
const allQuestions=[...portraitQuestions,...triviaQuestions];
const typeNames={portrait:'זהה את הדמות',knowledge:'ידע היסטורי',date:'שנים ותאריכים',earlier:'מה קרה קודם?',truefalse:'נכון או לא נכון'};
let activeQuestions=[],index=0,score=0,answered=false,audioContext=null;
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function getAudioContext(){if(!audioContext){const A=window.AudioContext||window.webkitAudioContext;if(A)audioContext=new A();}return audioContext;}
function playTone(f,s,d,t='sine',v=.12){const c=getAudioContext();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.setValueAtTime(f,s);g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(v,s+.015);g.gain.exponentialRampToValueAtTime(.0001,s+d);o.connect(g);g.connect(c.destination);o.start(s);o.stop(s+d+.02);}
function playCorrectSound(){const c=getAudioContext();if(!c)return;if(c.state==='suspended')c.resume();const n=c.currentTime+.02;playTone(523.25,n,.16,'triangle',.11);playTone(659.25,n+.12,.16,'triangle',.11);playTone(783.99,n+.24,.30,'triangle',.13);}
function playWrongSound(){const c=getAudioContext();if(!c)return;if(c.state==='suspended')c.resume();const n=c.currentTime+.02;playTone(220,n,.22,'sawtooth',.07);playTone(164.81,n+.16,.34,'sawtooth',.06);}
const $=id=>document.getElementById(id),setup=$('setup'),game=$('game'),result=$('result'),typeSelect=$('typeSelect'),categorySelect=$('categorySelect'),difficultySelect=$('difficultySelect'),setupMessage=$('setupMessage'),startGameButton=$('startGame'),portrait=$('portrait'),portraitFrame=$('portraitFrame'),caption=$('sourceCaption'),questionText=$('questionText'),answers=$('answers'),feedback=$('feedback'),next=$('next'),restart=$('restart'),playAgain=$('playAgain'),questionNumber=$('questionNumber'),totalQuestions=$('totalQuestions'),scoreNode=$('score'),finalScore=$('finalScore'),finalTotal=$('finalTotal'),typeTag=$('typeTag'),categoryTag=$('categoryTag'),difficultyTag=$('difficultyTag');
function updateDifficultyOptions(){const cat=categorySelect.value,type=typeSelect.value;const pool=allQuestions.filter(q=>(type==='all'||q.type===type)&&(cat==='all'||q.categories.includes(cat)));const available=new Set(pool.map(q=>q.difficulty)),previous=difficultySelect.value;difficultySelect.innerHTML='<option value="all">כל הרמות</option>';['קל','בינוני','קשה'].forEach(level=>{if(available.has(level)){const o=document.createElement('option');o.value=level;o.textContent=level;difficultySelect.appendChild(o);}});difficultySelect.value=available.has(previous)?previous:'all';setupMessage.textContent='';}
function startGame(){const type=typeSelect.value,cat=categorySelect.value,diff=difficultySelect.value;const filtered=allQuestions.filter(q=>(type==='all'||q.type===type)&&(cat==='all'||q.categories.includes(cat))&&(diff==='all'||q.difficulty===diff));if(!filtered.length){setupMessage.textContent='אין כרגע שאלות בשילוב הזה.';return;}activeQuestions=shuffle(filtered);index=0;score=0;setup.classList.add('hidden');result.classList.add('hidden');game.classList.remove('hidden');totalQuestions.textContent=activeQuestions.length;finalTotal.textContent=activeQuestions.length;renderQuestion();}
function renderQuestion(){answered=false;next.disabled=true;feedback.className='feedback';feedback.textContent='';const q=activeQuestions[index];questionNumber.textContent=index+1;scoreNode.textContent=score;typeTag.textContent=typeNames[q.type];categoryTag.textContent=q.categories.join(' · ');difficultyTag.textContent='רמה: '+q.difficulty;questionText.textContent=q.question;answers.innerHTML='';caption.hidden=true;if(q.type==='portrait'){portraitFrame.classList.remove('hidden');portrait.src=q.image;portrait.alt='דיוקן לזיהוי — שאלה '+(index+1);}else{portraitFrame.classList.add('hidden');portrait.removeAttribute('src');}shuffle(q.options).forEach(option=>{const b=document.createElement('button');b.type='button';b.textContent=option;b.addEventListener('click',()=>chooseAnswer(b,option));answers.appendChild(b);});next.textContent=index===activeQuestions.length-1?'לתוצאה':'לשאלה הבאה';}
function chooseAnswer(clicked,option){if(answered)return;answered=true;const q=activeQuestions[index];[...answers.children].forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add('correct');});if(option===q.answer){score++;scoreNode.textContent=score;playCorrectSound();feedback.innerHTML='<strong>נכון! ✅</strong><br>'+q.explanation;}else{clicked.classList.add('wrong');playWrongSound();feedback.innerHTML='<strong>לא הפעם ❌</strong><br>התשובה הנכונה היא <b>'+q.answer+'</b>.<br>'+q.explanation;}if(q.type==='portrait'){caption.textContent=q.source;caption.hidden=false;}feedback.classList.add('show');next.disabled=false;}
function showResult(){game.classList.add('hidden');result.classList.remove('hidden');finalScore.textContent=score;}
function backToSetup(){game.classList.add('hidden');result.classList.add('hidden');setup.classList.remove('hidden');setupMessage.textContent='';updateDifficultyOptions();}
next.addEventListener('click',()=>{if(!answered)return;if(index<activeQuestions.length-1){index++;renderQuestion();}else showResult();});restart.addEventListener('click',backToSetup);playAgain.addEventListener('click',backToSetup);startGameButton.addEventListener('click',startGame);categorySelect.addEventListener('change',updateDifficultyOptions);typeSelect.addEventListener('change',updateDifficultyOptions);portrait.addEventListener('error',()=>{caption.textContent='לא ניתן לטעון את התמונה כרגע. נסה לרענן.';caption.hidden=false;});updateDifficultyOptions();
